import { BrokerProfile } from "./broker-config-types";

export const CAPITAL_COM_PROFILE: BrokerProfile = {
  key: "CAPITAL_COM",
  name: "Capital.com",
  shortName: "Capital",
  regulation: "FCA / CySEC / ASIC (Retail CFD)",
  accountMode: "DEMO",
  accountType: "CFD Retail",
  baseCurrency: "USD",
  commission: "Spread only (no separate commission)",
  color: "#00c3ff",
  symbols: [
    {
      symbol: "XAUUSD",
      symbolLabel: "Gold / USD",
      leverage: 20,
      leverageLabel: "1:20",
      spreadTypical: 0.4,
      spreadUnit: "USD/oz",
      commissionPerLot: 0,
      marginPercent: 5.0,
      notes: "EU retail limit 1:20. Overnight funding applies.",
    },
    {
      symbol: "EURUSD",
      symbolLabel: "EUR / USD",
      leverage: 30,
      leverageLabel: "1:30",
      spreadTypical: 0.9,
      spreadUnit: "pips",
      commissionPerLot: 0,
      marginPercent: 3.33,
      notes: "EU retail max 1:30 for major forex pairs.",
    },
    {
      symbol: "NAS100",
      symbolLabel: "NASDAQ 100",
      leverage: 20,
      leverageLabel: "1:20",
      spreadTypical: 1.5,
      spreadUnit: "points",
      commissionPerLot: 0,
      marginPercent: 5.0,
      notes: "US equity index. EU limit 1:20.",
    },
    {
      symbol: "USOIL",
      symbolLabel: "WTI Crude Oil",
      leverage: 10,
      leverageLabel: "1:10",
      spreadTypical: 0.05,
      spreadUnit: "USD/bbl",
      commissionPerLot: 0,
      marginPercent: 10.0,
      notes: "Commodity. EU limit 1:10.",
    },
    {
      symbol: "BTCUSD",
      symbolLabel: "Bitcoin / USD",
      leverage: 2,
      leverageLabel: "1:2",
      spreadTypical: 20,
      spreadUnit: "USD",
      commissionPerLot: 0,
      marginPercent: 50.0,
      notes: "Crypto CFD. EU max 1:2.",
    },
    {
      symbol: "SPX500",
      symbolLabel: "S&P 500",
      leverage: 20,
      leverageLabel: "1:20",
      spreadTypical: 0.5,
      spreadUnit: "points",
      commissionPerLot: 0,
      marginPercent: 5.0,
      notes: "US equity index. EU limit 1:20.",
    },
  ],
};

export const IC_MARKETS_PROFILE: BrokerProfile = {
  key: "IC_MARKETS",
  name: "IC Markets",
  shortName: "IC Markets",
  regulation: "ASIC / CySEC / FSA (ECN/STP)",
  accountMode: "DEMO",
  accountType: "Raw Spread ECN",
  baseCurrency: "USD",
  commission: "$7 per lot round-turn (Raw Spread accounts)",
  color: "#10c96d",
  symbols: [
    {
      symbol: "XAUUSD",
      symbolLabel: "Gold / USD",
      leverage: 500,
      leverageLabel: "1:500",
      spreadTypical: 0.12,
      spreadUnit: "USD/oz",
      commissionPerLot: 7,
      marginPercent: 0.2,
      notes: "Raw ECN spread. $7/lot commission. Non-EU accounts.",
    },
    {
      symbol: "EURUSD",
      symbolLabel: "EUR / USD",
      leverage: 500,
      leverageLabel: "1:500",
      spreadTypical: 0.1,
      spreadUnit: "pips",
      commissionPerLot: 7,
      marginPercent: 0.2,
      notes: "Raw spread often 0.0-0.2 pips + $7/lot commission.",
    },
    {
      symbol: "NAS100",
      symbolLabel: "NASDAQ 100",
      leverage: 200,
      leverageLabel: "1:200",
      spreadTypical: 0.3,
      spreadUnit: "points",
      commissionPerLot: 7,
      marginPercent: 0.5,
      notes: "Index CFD via Raw ECN. Very tight spread.",
    },
    {
      symbol: "USOIL",
      symbolLabel: "WTI Crude Oil",
      leverage: 200,
      leverageLabel: "1:200",
      spreadTypical: 0.03,
      spreadUnit: "USD/bbl",
      commissionPerLot: 7,
      marginPercent: 0.5,
      notes: "Commodity CFD. Raw ECN pricing.",
    },
    {
      symbol: "BTCUSD",
      symbolLabel: "Bitcoin / USD",
      leverage: 2,
      leverageLabel: "1:2",
      spreadTypical: 10,
      spreadUnit: "USD",
      commissionPerLot: 7,
      marginPercent: 50.0,
      notes: "Crypto: max 1:2 even on IC Markets.",
    },
    {
      symbol: "SPX500",
      symbolLabel: "S&P 500",
      leverage: 200,
      leverageLabel: "1:200",
      spreadTypical: 0.2,
      spreadUnit: "points",
      commissionPerLot: 7,
      marginPercent: 0.5,
      notes: "Index CFD Raw ECN.",
    },
  ],
};

export const ALL_BROKER_PROFILES: BrokerProfile[] = [
  CAPITAL_COM_PROFILE,
  IC_MARKETS_PROFILE,
];
