import {
  DependencyItem,
  DependencyScannerReport,
} from "./dependency-scanner-types";

const dependencyItems: DependencyItem[] = [
  {
    id: "gpt-analyst",
    name: "GPT Analyst",
    layer: "AI",
    apiRoute: "/api/gpt-analyst/analyze",
    status: "ACTIVE",
    healthStatus: "HEALTHY",
    dependsOn: ["market-data", "news-intelligence", "economic-calendar"],
    feedsInto: ["consensus", "portfolio-brain", "evolution-center"],
    notificationRequired: false,
    telegramAlertReady: true,
    note: "Main OpenAI/GPT analysis layer.",
  },
  {
    id: "claude-risk",
    name: "Claude Risk",
    layer: "AI",
    apiRoute: "/api/claude-risk/assess",
    status: "ACTIVE",
    healthStatus: "HEALTHY",
    dependsOn: ["market-data", "portfolio-risk-management"],
    feedsInto: ["consensus", "portfolio-brain"],
    notificationRequired: false,
    telegramAlertReady: true,
    note: "Risk validation layer planned for Claude-based risk checks.",
  },
  {
    id: "consensus",
    name: "Consensus Engine",
    layer: "AI",
    apiRoute: "/api/consensus/decision",
    status: "ACTIVE",
    healthStatus: "HEALTHY",
    dependsOn: ["gpt-analyst", "claude-risk"],
    feedsInto: ["portfolio-brain"],
    notificationRequired: false,
    telegramAlertReady: true,
    note: "Combines GPT and Claude outputs.",
  },
  {
    id: "portfolio-brain",
    name: "Portfolio Brain",
    layer: "PORTFOLIO",
    apiRoute: "/api/portfolio-brain",
    status: "ACTIVE",
    healthStatus: "HEALTHY",
    dependsOn: ["consensus", "portfolio-risk-management"],
    feedsInto: ["evolution-allocation-portfolio-sync"],
    notificationRequired: false,
    telegramAlertReady: true,
    note: "Main portfolio decision layer.",
  },
  {
    id: "evolution-center",
    name: "Evolution Center",
    layer: "EVOLUTION",
    component: "EvolutionCenterPanel.tsx",
    status: "CENTER_ACTIVE",
    healthStatus: "HEALTHY",
    dependsOn: [
      "mutation-competition",
      "strategy-breeding",
      "strategy-species-classification",
      "evolution-allocation"
    ],
    feedsInto: ["execution-center", "broker-center", "learning-center"],
    notificationRequired: false,
    telegramAlertReady: true,
    note: "Clean center shell and detail dashboard for Evolution pipeline.",
  },
  {
    id: "evolution-allocation",
    name: "Evolution Allocation",
    layer: "EVOLUTION",
    apiRoute: "/api/evolution-allocation",
    component: "EvolutionAllocationDashboardPanel.tsx",
    status: "ACTIVE",
    healthStatus: "HEALTHY",
    dependsOn: ["evolution-governance"],
    feedsInto: ["evolution-allocation-portfolio-sync"],
    notificationRequired: false,
    telegramAlertReady: true,
    note: "Normalized Species allocation.",
  },
  {
    id: "species-capital-allocation",
    name: "Species Capital Allocation",
    layer: "EVOLUTION",
    apiRoute: "/api/species-capital-allocation",
    component: "SpeciesCapitalAllocationPanel.tsx",
    status: "ACTIVE",
    healthStatus: "HEALTHY",
    dependsOn: ["evolution-allocation-portfolio-sync"],
    feedsInto: ["species-position-sizing"],
    notificationRequired: false,
    telegramAlertReady: true,
    note: "Converts portfolio weights into simulated capital allocations.",
  },
  {
    id: "species-position-sizing",
    name: "Species Position Sizing",
    layer: "EVOLUTION",
    apiRoute: "/api/species-position-sizing",
    component: "SpeciesPositionSizingPanel.tsx",
    status: "ACTIVE",
    healthStatus: "HEALTHY",
    dependsOn: ["species-capital-allocation"],
    feedsInto: ["species-trade-allocation"],
    notificationRequired: false,
    telegramAlertReady: true,
    note: "Converts capital allocation into position sizing.",
  },
  {
    id: "species-trade-allocation",
    name: "Species Trade Allocation",
    layer: "EVOLUTION",
    apiRoute: "/api/species-trade-allocation",
    component: "SpeciesTradeAllocationPanel.tsx",
    status: "ACTIVE",
    healthStatus: "HEALTHY",
    dependsOn: ["species-position-sizing"],
    feedsInto: ["species-execution-queue"],
    notificationRequired: false,
    telegramAlertReady: true,
    note: "Creates trade slots from Species position sizing.",
  },
  {
    id: "species-execution-queue",
    name: "Species Execution Queue",
    layer: "EXECUTION",
    apiRoute: "/api/species-execution-queue",
    status: "ACTIVE",
    healthStatus: "HEALTHY",
    dependsOn: ["species-trade-allocation"],
    feedsInto: ["species-execution-center-sync"],
    notificationRequired: false,
    telegramAlertReady: true,
    note: "Creates ranked execution queue tickets.",
  },
  {
    id: "species-live-execution-bridge",
    name: "Species Live Execution Bridge",
    layer: "EXECUTION",
    apiRoute: "/api/species-live-execution-bridge",
    component: "SpeciesLiveExecutionBridgePanel.tsx",
    status: "ACTIVE",
    healthStatus: "HEALTHY",
    dependsOn: ["species-execution-queue-integration"],
    feedsInto: ["species-broker-execution-sync"],
    notificationRequired: false,
    telegramAlertReady: true,
    note: "Bridge between Species queue and live execution simulation.",
  },
  {
    id: "species-broker-execution-sync",
    name: "Species Broker Execution Sync",
    layer: "BROKER",
    apiRoute: "/api/species-broker-execution-sync",
    status: "ACTIVE",
    healthStatus: "HEALTHY",
    dependsOn: ["species-live-execution-bridge"],
    feedsInto: ["broker-routing-layer", "future-execution-confirmation"],
    notificationRequired: false,
    telegramAlertReady: true,
    note: "Dispatch-ready sync layer for broker execution.",
  },
  {
    id: "broker-center",
    name: "Broker Center",
    layer: "BROKER",
    status: "CENTER_ACTIVE",
    healthStatus: "HEALTHY",
    dependsOn: ["smart-broker-selection", "broker-routing-layer"],
    feedsInto: ["species-broker-execution-sync", "future-execution-confirmation"],
    notificationRequired: false,
    telegramAlertReady: true,
    note: "Future home for broker routing, health, latency and connector status.",
  },
  {
    id: "learning-center",
    name: "Learning Center",
    layer: "LEARNING",
    status: "CENTER_ACTIVE",
    healthStatus: "HEALTHY",
    dependsOn: ["trade-outcome-feedback-engine", "learning-feedback-integration"],
    feedsInto: ["gpt-analyst", "claude-risk", "portfolio-brain", "evolution-center"],
    notificationRequired: false,
    telegramAlertReady: true,
    note: "Future AI memory and feedback loop center.",
  },
  {
    id: "dynamic-position-allocation",
    name: "Dynamic Position Allocation",
    layer: "LEGACY",
    apiRoute: "/api/dynamic-position-allocation",
    component: "DynamicPositionAllocationPanel.tsx",
    status: "LEGACY_REVIEW",
    healthStatus: "WARNING",
    dependsOn: [],
    feedsInto: [],
    notificationRequired: true,
    telegramAlertReady: true,
    note: "Legacy review candidate. New Species Position Sizing may replace this.",
  },
  {
    id: "trading-style-priority",
    name: "Trading Style Priority",
    layer: "LEGACY",
    apiRoute: "/api/trading-style-priority-engine",
    component: "TradingStylePriorityDashboardPanel.tsx",
    status: "LEGACY_REVIEW",
    healthStatus: "WARNING",
    dependsOn: [],
    feedsInto: [],
    notificationRequired: true,
    telegramAlertReady: true,
    note: "Legacy review candidate. Needs dependency check before archive.",
  },
  {
    id: "multi-timeframe-sync",
    name: "Multi Timeframe Sync",
    layer: "LEGACY",
    apiRoute: "/api/multi-timeframe-unified-decision-sync",
    status: "LEGACY_REVIEW",
    healthStatus: "WARNING",
    dependsOn: [],
    feedsInto: [],
    notificationRequired: true,
    telegramAlertReady: true,
    note: "Legacy review candidate. Keep API available until checked.",
  },
];

function countBy<T extends string>(
  items: DependencyItem[],
  selector: (item: DependencyItem) => T,
  value: T
): number {
  return items.filter((item) => selector(item) === value).length;
}

export function getDependencyScannerReport(): DependencyScannerReport {
  const totalItems = dependencyItems.length;

  return {
    version: "V15.A.5",
    status: "READY",
    mode: "SIMULATION",
    totalItems,
    activeItems: countBy(dependencyItems, (item) => item.status, "ACTIVE"),
    centerActiveItems: countBy(
      dependencyItems,
      (item) => item.status,
      "CENTER_ACTIVE"
    ),
    legacyReviewItems: countBy(
      dependencyItems,
      (item) => item.status,
      "LEGACY_REVIEW"
    ),
    mergeTargetItems: countBy(
      dependencyItems,
      (item) => item.status,
      "MERGE_TARGET"
    ),
    archiveLaterItems: countBy(
      dependencyItems,
      (item) => item.status,
      "ARCHIVE_LATER"
    ),
    healthyItems: countBy(dependencyItems, (item) => item.healthStatus, "HEALTHY"),
    warningItems: countBy(dependencyItems, (item) => item.healthStatus, "WARNING"),
    criticalItems: countBy(dependencyItems, (item) => item.healthStatus, "CRITICAL"),
    notificationRequiredItems: dependencyItems.filter(
      (item) => item.notificationRequired
    ).length,
    telegramReadyItems: dependencyItems.filter((item) => item.telegramAlertReady)
      .length,
    dependencyItems,
    futureTelegramAlertPlan: {
      enabledNow: false,
      planned: true,
      trigger:
        "When an engine/API healthStatus becomes WARNING or CRITICAL, create Telegram alert event.",
      target: "TELEGRAM",
      messageTemplate:
        "AI Trading System Alert: {{module}} is {{healthStatus}}. Layer: {{layer}}. Action: check dependency scanner.",
    },
    summary:
      "Dependency Scanner is ready as a future health-monitor and Telegram-alert foundation. No engines are deleted or modified.",
  };
}
